### ISSUE TITLE
The app crashes on any pdf file on 4.4.4

### ISSUE THREAD

**Issue by KOLANICH** [SufficientlySecure/document-viewer#180]
```

Application information:

This file was generated by the org.sufficientlysecure.viewer.2.7.4(2747)

Device information:

VERSION     : 19
BOARD       : smdk4x12
BRAND       : samsung
CPU_ABI     : null
CPU_ABI2    : null
DEVICE      : 
DISPLAY     : cm_n7100-userdebug 4.4.4
FINGERPRINT : samsung/
ID          : 
MANUFACTURER: null
MODEL       : GT-N7100

Error information:

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.viewer/org.ebookdroid.ui.viewer.ViewerActivity}: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5146)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at org.ebookdroid.core.models.DocumentModel.<init>(DocumentModel.java:71)
	at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:238)
	at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:94)
	at org.emdev.ui.AbstractActionActivity.onCreate(AbstractActionActivity.java:107)
	at android.app.Activity.performCreate(Activity.java:5231)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
	... 12 more
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1208)
	at org.ebookdroid.core.models.DocumentModel.<init>(DocumentModel.java:68)
	... 18 more
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Couldn't load ebookdroid from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.sufficientlysecure.viewer-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.sufficientlysecure.viewer-1, /vendor/lib, /system/lib]]]: findLibrary returned null
	at org.ebookdroid.EBookDroidLibraryLoader.load(EBookDroidLibraryLoader.java:21)
	at org.ebookdroid.droids.mupdf.codec.MuPdfContext.<clinit>(MuPdfContext.java:24)
	... 21 more
Caused by: java.lang.UnsatisfiedLinkError: Couldn't load ebookdroid from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.sufficientlysecure.viewer-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.sufficientlysecure.viewer-1, /vendor/lib, /system/lib]]]: findLibrary returned null
	at java.lang.Runtime.loadLibrary(Runtime.java:358)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at java.lang.Runtime.loadLibrary(Native Method)
	at java.lang.System.loadLibrary(System.java:526)
	at org.ebookdroid.EBookDroidLibraryLoader.load(EBookDroidLibraryLoader.java:17)
	... 22 more

```

**Comment by ericwa** [comment]
Looks like the native library isn't loading.
Is this an apk from Google Play or F-Droid?

`cm_n7100-userdebug` means cyanogenmod? I wonder why CPU_ABI and CPU_ABI2 are null.

**Comment by ericwa** [comment]
Hmm, I can't reproduce this, flashed my Nexus 4 with cyanogenmod 11 (android 4.4.4) `cm-11-20141115-SNAPSHOT-M12-mako` and both the F-Droid and Play Store APK's can display pdf's.

**Comment by KOLANICH** [comment]
>Is this an apk from Google Play or F-Droid?

it's from F-Droid.

>cm_n7100-userdebug means cyanogenmod?

yes. CM 11.
