### ISSUE TITLE
Crashes during search if split-pages is enabled

### ISSUE THREAD

**Issue by a--v--k** [SufficientlySecure/document-viewer#19]
https://code.google.com/p/ebookdroid/issues/detail?id=460

What steps will reproduce the problem?
1. open a two-column pdf with split-pages enabled.
2. Search for a string of text.
3. The display moves and highlights a region (sometimes the wong one!)
4. Select arrow to find the next match.
5. EbookDroid closes.

What is the expected output?
I expected search to work as usual.  It does work if I disable split-pages.

What do you see instead?
Program closes.

What version of the product are you using?
1.6.6

On what operating system?

What device are you using?

Please provide any additional information below.

**Comment by tuxor1337** [comment]
Confirmed. Output from logcat:

    W/dalvikvm( 4412): threadid=12: thread exiting with uncaught exception (group=0x41858ce0)
    I/System.out( 4412): Stacktrace is written: /storage/emulated/0/.org.sufficientlysecure.viewer/logs/org.sufficientlysecure.viewer.2.5.20150129.004700.stacktrace
    E/AndroidRuntime( 4412): FATAL EXCEPTION: GLThread 209
    E/AndroidRuntime( 4412): Process: org.sufficientlysecure.viewer, PID: 4412
    E/AndroidRuntime( 4412): java.lang.NullPointerException
    E/AndroidRuntime( 4412): 	at org.ebookdroid.core.EventGLDraw.drawHighlights(EventGLDraw.java:209)
    E/AndroidRuntime( 4412): 	at org.ebookdroid.core.EventGLDraw.process(EventGLDraw.java:103)
    E/AndroidRuntime( 4412): 	at org.ebookdroid.core.AbstractScrollController.drawView(AbstractScrollController.java:49)
    E/AndroidRuntime( 4412): 	at org.ebookdroid.core.EventGLDraw.process(EventGLDraw.java:77)
    E/AndroidRuntime( 4412): 	at org.ebookdroid.ui.viewer.viewers.GLView.draw(GLView.java:67)
    E/AndroidRuntime( 4412): 	at org.emdev.ui.gl.GLRootView.onDrawFrameLocked(GLRootView.java:195)
    E/AndroidRuntime( 4412): 	at org.emdev.ui.gl.GLRootView.onDrawFrame(GLRootView.java:171)
    E/AndroidRuntime( 4412): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1525)
    E/AndroidRuntime( 4412): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1242)
